# googleAnalytics = "G-CVK51TGZ0B"
baseurl = "https://teckperry.xyz/"
languageCode = "it"
title = "Teckperry's Blog"
theme = "archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5

# Theme Params
[params]
  # color-mode → light, dark or auto
	mode="light"
	featherIconsCDN=true
	subtitle = "0100 1000 0100 0101 0100 1100 0100 1100 0100 1111 0101 0111 0100 1111 0101 0010 0100 1100 0100 0100 0010 0001"

# Social Tags
[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/teckperry"

[[params.social]]
name = "Twitch"
icon = "twitch"
url = "https://www.twitch.tv/teckperry"

[[params.social]]
name = "Discord"
icon = "discord"
url = ""

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

[[menu.main]]
name = "Links"
url = "/links"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# [[menu.main]]
# name = "Cookies"
# url = "/cookies"
# weight = 5

# [[menu.main]]
# name = "Privacy"
# url = "/privacy"
# weight = 6

[deployment]
order = [".jpg$", ".gif$"]

# Privacy Settings
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false